# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{config, pkgs, ...}: with pkgs;

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" "fbcon" ];
  boot.extraModulePackages = [ ];

  # Use the gummiboot efi boot loader.
  boot.loader.gummiboot.enable = true;
  boot.loader.gummiboot.timeout = 5;
  boot.loader.efi.canTouchEfiVariables = true;

  # Encrypt whole disk
  boot.initrd.luks.devices = [
    {
      name = "root"; device = "/dev/sda3"; preLVM = false;
    }
  ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-label/var";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { 
      device = "/dev/disk/by-label/home";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { 
      device = "/dev/disk/by-label/UEFI";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-label/swap"; 
    }
  ];

  nix.maxJobs = 4;
}
