# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ 
    "ahci"
    "ehci_pci" 
    "nls_cp437"
    "nls_iso8859-1"
    "usb_storage"
    "usbhid"
    "xhci_hcd"
    "vfat"
  ];
  boot.kernelModules = [ "kvm-intel" "fbcon" ];
  boot.extraModulePackages = [ ];
  
  # luks
  boot.initrd.luks.yubikeySupport = true;
  boot.initrd.luks.cryptoModules = [
    "aes"
    "xts"
    "sha512"
  ];
  boot.initrd.luks.devices = [{
    name = "enc-pv";
    device = "/dev/sda2";
    preLVM = true;
    # yubikey = {
    #   storage = {
    #     device = "/dev/sda1";
    #   };
    # };
  }];
  
  # Use the gummiboot efi boot loader.
  boot.loader.gummiboot.enable = true;
  boot.loader.gummiboot.timeout = 5;
  boot.loader.efi.canTouchEfiVariables = true;

  # sound
  boot.extraModprobeConfig = ''
      options snd_hda_intel enable=0,1
  '';

  fileSystems."/" =
    { 
      device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { 
      device = "/dev/disk/by-label/UEFI";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

  nix.maxJobs = 4;
}
